[package]
name = "rate-counter"
version = "0.1.0"
authors = ["Bryan Stitt <bryan@llamanodes.com>"]
edition = "2021"

[dependencies]
kanal = "0.1.0-pre8"
tokio = { version = "1.28.1", features = ["time"] }
