#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod ierc20;
pub mod payment_factory;
pub mod payment_proxy;
pub mod payment_sweeper;
