//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "rpc_accounting")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_key_id: u64,
    pub chain_id: u64,
    pub timestamp: DateTimeUtc,
    pub method: String,
    pub backend_requests: u32,
    pub error_response: i8,
    pub query_millis: u32,
    pub request_bytes: u32,
    pub response_bytes: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_keys::Entity",
        from = "Column::UserKeyId",
        to = "super::user_keys::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserKeys,
}

impl Related<super::user_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserKeys.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
